# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Devlog
tagline:          'Game Development Blog'
description:      'Personal game development blog .'
url:              http://voodoocactus.com/devlog
baseurl:          /devlog/

author:
  name:           'Laurent Zubiaur'
  url:            https://twitter.com/laurentzubiaur

company:
    name:         'Voodoo Cactus'
    url:          http://voodoocactus.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lzubiaur
