# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Devlog
tagline:          'Development Blog'
description:      'Personal development blog by <a href="https://twitter.com/laurentzubiaur" target="_blank">@laurentzubiaur</a>'
url:              https://lzubiaur.github.com/devlog
baseurl:          /devlog/

rss:              /devlog/atom.xml

author:
  name:           'Laurent Zubiaur'
  url:            https://twitter.com/laurentzubiaur
  email:          zubiaur.laurent@gmail.com
  tumblr:         http://blog.voodoocactus.com/
  youtube:        https://www.youtube.com/user/zubifies
  facebook:       https://www.facebook.com/voodocactustudio

company:
    name:         'Voodoo Cactus'
    url:          http://voodoocactus.com/

disqus:
        shortname: 'gamedevlog'

paginate:         5

# Custom vars
version:          1.2.0

github:
  repo:           https://github.com/lzubiaur
