# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Devlog
tagline:          'Game Development Blog'
description:      'Personal game development blog by <a href="https://twitter.com/laurentzubiaur" target="_blank">@laurentzubiaur</a>'
url:              http://voodoocactus.com/devlog
baseurl:          /devlog/

author:
  name:           'Laurent Zubiaur'
  url:            https://twitter.com/laurentzubiaur
  email:          laurentzubiaur@voodoocactus.com

company:
    name:         'Voodoo Cactus'
    url:          http://voodoocactus.com/

disqus:
        shortname: 'laurentzubiaur'

paginate:         5

# Custom vars
version:          1.2.0

github:
  repo:           https://github.com/lzubiaur
